name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_audio/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_audio/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 3
      matrix:
        python-version: [ "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig sox mpg123
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install .[extras]
      - name: Install test dependencies
        run: |
          pip install -r test/requirements.txt
      - name: Run unittests
        run: |
          pytest --cov=ovos_audio --cov-report xml test/unittests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: OpenVoiceOS/ovos-audio
